name: CI/CD

on:
  push:
    branches:
      - main  # Change this to match your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ec2-host-dns: ${{secrets.EC2_HOST_DNS}}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} Ubuntu@${{secrets.EC2_HOST_DNS}} 'bash -s' << 'ENDSSH'
          cd /apps/
          git pull origin main
          cd /apps/services
          yarn install
          pm2 restart <your_app_name>
        ENDSSH

